# Generated by Django 3.1 on 2020-11-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='ingredientes',
        ),
        migrations.CreateModel(
            name='IngredientPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizzaria.ingredient')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizzaria.pizza')),
            ],
        ),
    ]
