# Generated by Django 3.1 on 2020-11-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0002_auto_20201120_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='ingredientes',
            field=models.ManyToManyField(through='pizzaria.IngredientPizza', to='pizzaria.Ingredient'),
        ),
    ]
