# Generated by Django 3.1 on 2020-11-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0003_pizza_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientpizza',
            name='measurem_unit',
            field=models.CharField(default='xicara(s) de chá', max_length=20, verbose_name='unidade de medida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredientpizza',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default='0.5', max_digits=10, verbose_name='quantidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descrição'),
        ),
    ]
