version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./__data/pgdata:/pgdata
    environment: 
      - PGDATA=/pgdata      
      - POSTGRES_DB=pizza_place
      - POSTGRES_USER=pizza_place
      - POSTGRES_PASSWORD=pizza_place
      - POSTGRES_HOST=db
      - TZ=America/Sao_Paulo
    ports:
      - 5432:5432